# builder image
FROM golang:1.18-alpine as builder

ENV GOPATH=/go \
  APP_PATH=/code \
  CODE_PATH=$APP_PATH/grpc_ports/portsvc \
  CGO_ENABLED=0 \
  GOFLAGS=-mod=vendor

# Copy source code to the container.
WORKDIR $CODE_PATH
COPY portsvc .

# build a binary
RUN go build -o ${GOPATH}/bin/portsvc ./cmd/grpc/main.go

# --- production stage ---
# https://hub.docker.com/_/alpine/
FROM alpine:3.13 AS production

# copy the built binary from the build process.
COPY --from=builder /go/bin/portsvc /usr/local/bin/portsvc

# run the binary.
CMD ["/usr/local/bin/portsvc"]

EXPOSE 50051
